### ISSUE TITLE
Can add support for these file formats

### ISSUE THREAD

**Issue by darvon123** [jesuscc1993/file-type-icons#1]
Scalable   Vector Graphic  

| ---- | ---- |
| Svg | Scalable Vector Graphic |
| Svgz | Scalable Vector Graphic [zipped compressed] |

3D Model files type   [USD]  
-------
| ---- | ---- |
| USD   | Universal Scene Description Format |
| USDA | Universal Scene Description Format ASCII [ASCII encoded] |
| USDC | Universal Scene Description Format Compilied [Binary encoded] |
| USDZ  | Universal Scene Description Format Zip archive |
------
3D Model file types   
|--|--|
|PLY | Polygon File Format|
|STL | STereoLithography|
|dae | Digital Asset Exchange File|
|glb | Graphics Library Binary [Graphics Library Transmission Format]|
|gltf | Graphics Library Transmission Format|

**Comment by jesuscc1993** [comment]
I don't plan on taking requests.
I have just pushed a template; feel free to make them yourself.
